language: python
#python:
# - "3.9"
before_install:
  - chmod +x ./flaskapp/st.sh
install:
  - pip3 install flask
  - pip3 install gunicorn
  - pip3 install requests
  - pip3 install flask-bootstrap
  - pip3 install flask-wtf
  - pip3 install pillow
  - pip3 install tensorflow==2.1
  - pip3 install keras==2.3.1
  - pip3 install lxml
script:
  - cd flaskapp
  - ./st.sh
